add_rules("mode.debug", "mode.release")
set_languages("c++17")
add_includedirs("src/")
add_requires("yaml-cpp", "gflags", "glog")

target("util")
    set_kind("static")
    add_files("src/util/*.cc")

target("logger")
    set_kind("static")
    add_files("src/logger/*.cc")

target("epoll_server")
    set_kind("static")
    add_files("src/epoll_server/*.cc")
    add_deps("logger", "util")
    add_packages("yaml-cpp")
    add_links("pthread")

target("fake-tcp-server")
    set_kind("binary")
    add_files("src/server/*.cc")
    add_deps("epoll_server", "logger")

target("fake-tcp-client")
    set_kind("binary")
    add_includedirs("src/")
    add_files("src/client/*.cc")
    add_packages("glog", "yaml-cpp")
    add_deps("util", "logger")
